FriendsOfREDAXO/feeds

pages/faq.php

https://github.com/yakamara/redaxo_yfeed/issues/14

Anleitung für automatischen Stream-Abruf

---

composer.json
lang/de_de.lang
lang/en_gb.lang
lib/stream/vimeo_pro_user.php

Vimeo-Pro user

---

lib/stream/facebook_feed.php

ungetestet! closes #63 
In diesen PR können ggf. weitere Änderungen eingepflegt werden.

facebook graph api version erhöhen

---

lib/stream/youtube_playlist.php

75 und 100 Items laut API-Fehlermeldung zu viel.

---

pages/items.php

Einträge Übersicht mit Bilder + Offline Indikator - Offline BS3 Classes integriert

---

README.md

Feed einhängen via Project-Addon

---

lib/stream/instagram_user.php

fix Tippfehler

---

lib/stream/twitter_hashtag.php
lib/stream/twitter_user_timeline.php

use media_url_https, closes #80

fix notice twitter streams

---

README.md

docs cronjob removing old items

---

lang/de_de.lang
lib/stream/facebook_events.php

Benötigt Feedback in #71 von @simonsinus wg. Abruf der Bilddatei.

WIP: Facebook Events auslesen

---

install.php

fix #118
bitte testen, ob ein Update von feeds 2.3 auf 3.0 gelingt.

make foreign keys great again

---

lang/de_de.lang
lib/stream/youtube_channel.php
lib/stream/youtube_playlist.php

closes #54 
closes #119
fix php-notice
catch errors => #40

fix youtube api key and catch errors

---

README.md
lib/item.php
lib/stream/abstract/instagram.php
lib/stream/facebook_events.php
lib/stream/facebook_feed.php
lib/stream/google_places.php
lib/stream/rss.php
lib/stream/twitter_hashtag.php
lib/stream/twitter_user_timeline.php
lib/stream/vimeo_pro_user.php
lib/stream/youtube_playlist.php
lib/stream_abstract.php

closes #129, bitte um Feedback / ungetestet.

add ep FEEDS_ITEM_SAVED & FEEDS_STREAM_FETCHED

---

lib/stream/twitter_hashtag.php
lib/stream/twitter_user_timeline.php

closes #142 
noch ungetestet. Vielleicht findet man noch die URL aus der API raus.

fix twitter url

---

install.php

siehe https://github.com/FriendsOfREDAXO/feeds/commit/89882c317aff0f78e74701414dbb45239f88e376#r36643777

Foreign keys fix

---

lib/media_manager_effect.php

Hier bisher ungetestet, ich habe es bisher nur im Core-PR für mediapath getestet: https://github.com/redaxo/redaxo/pull/3735

MM-Effekt: Korrekten Dateinamen nehmen

---

lib/stream/facebook_feed.php

Fix switch statement on attachment type in order to fix fetching images from facebook posts.

Fix switch statement on attachment type

---

lib/stream/rss.php

fix missing image in rss feed

---

install.php

so richtig @gharlan? 
Konnte es aktuell nicht testen. 
close #156

install added: rex_sql_foreign_key::CASCADE

---

README.md

Sollte ohne Anpassungen sofort funktionieren

Beispielcode überarbeitet.

---

lib/stream/ics.php

Es gibt Szenarien, in denen ein iCal-Kalenderdaten-Import interessant sein kann. Ich hatte mir da mal was gebaut. Hier ein Basic Ansatz für den iCal Import, ohne Vendor.

iCal als Importquelle

---

lang/de_de.lang
pages/items.php

added search for items

---

lib/stream/rss.php

Support für Mastodon Feeds. 
Bilder aus Mastodon werden übernommen. Videos ausgelassen.

Mastodon fix

---

lib/item.php

```php
$mediaInfo = $item->getMediaInfo('mein_media_type'); 
if ($mediaInfo) {
echo "Breite: " . $mediaInfo['width'];
echo "Höhe: " . $mediaInfo['height'];
echo "Format: " . $mediaInfo['format'];
}
```

new getMediaInfo
